# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alberto Antonio Romero
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Alberto Antonio Romero es de Esquel, Chubut, nació en 1988. Egresado de la carrera de Dramaturgia de EMAD. Realizó residencias en dramaturgia, curaduría y dirección en Argentina y México. Mención Premio Ronzenmacher a la nueva dramaturgia (FIBA), II Premio dramaturgia regional (INT). Trabaja como performer para reconocidxs artistxs. Como director estrenó: Canadá, 3., El Convite, Malviaje, Alwe y Nube Petróleo. Fue asistente de Alejandro Tantanián y Silvio Lang. Su poemario Teatra fue editado por Ediciones desde un tacho. Trabajó en proyectos para GAM (Chile), MAMBA, ORTEUV (México), CCR, Bienal de Arte Joven de BA, Casa del Bicentenario. En artes visuales paticipó de las muestras colectivas Geométrica y Barata; y Ni plata ni miedo, que los días sean más que todo lo que tenemos. Presentó La espada y la piedra, en el ciclo de acciones de Munar El asunto de lo remoto, con curaduría de Gonzalo Lagos. Fue seleccionado para el Programa de Artistas CIA 2017. Actualmente participa como curador del Programa de artistas 2018 de la Universidad Torcuato Di Tella. Director de la colección Gallinero de dramaturgia contemporánea, de Rara Avis editorial. Es director y curador junto a Martín Fernández, de Constitución galería.


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
